In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score

#### Load the dataset and preview

In [ ]:
df = pd.read_csv(r'C:\Users\user\Documents\Applied Machine learning\Iris.csv', sep=';', header=None)

In [ ]:
df.head()

,0,1,2,3,4
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
 4   4       150 non-null    str    
dtypes: float64(4), str(1)
memory usage: 6.0 KB


In [ ]:
X1 = df.iloc[:, 0:3]
print(X1)

       0    1    2
0    5.1  3.5  1.4
1    4.9  3.0  1.4
2    4.7  3.2  1.3
3    4.6  3.1  1.5
4    5.0  3.6  1.4
..   ...  ...  ...
145  6.7  3.0  5.2
146  6.3  2.5  5.0
147  6.5  3.0  5.2
148  6.2  3.4  5.4
149  5.9  3.0  5.1

[150 rows x 3 columns]


In [ ]:
y1 = df.iloc[:, 4]
print(y1)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 4, Length: 150, dtype: str


In [ ]:
encoder = OneHotEncoder(sparse_output =False)
y1_encoded = encoder.fit_transform(y1.values.reshape(-1, 1))
print(y1_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

#### MinMax Normalisation

In [ ]:
scaler = MinMaxScaler()
X1_scaled = scaler.fit_transform(X1)

#### Data Split

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X1_scaled, y1_encoded, test_size=0.5, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

#### Neural Network

In [ ]:
model = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', solver='adam',
    max_iter=500, warm_start=True,random_state=42)

In [ ]:
epochs = 100
for i in range(1, epochs + 1):

    model.fit(X_train, y_train)
    
    train_prediction = model.predict(X_train)
    val_pred = model.predict(X_val)
    train_loss = np.sum((train_prediction - y_train) ** 2)
    val_loss = np.sum((val_pred - y_val) ** 2) 
    print(f"Epoch {i:02d} -> Train Sum-of-Squares Lo.ss: {train_loss:.4f} | Validation Sum-of-Squares Loss: {val_loss:.4f}")

     

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Epoch 01 -> Train Sum-of-Squares Lo.ss: 40.0000 | Validation Sum-of-Squares Loss: 17.0000


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Epoch 02 -> Train Sum-of-Squares Lo.ss: 22.0000 | Validation Sum-of-Squares Loss: 12.0000


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Epoch 03 -> Train Sum-of-Squares Lo.ss: 13.0000 | Validation Sum-of-Squares Loss: 7.0000


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Epoch 04 -> Train Sum-of-Squares Lo.ss: 6.0000 | Validation Sum-of-Squares Loss: 4.0000


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Epoch 05 -> Train Sum-of-Squares Lo.ss: 5.0000 | Validation Sum-of-Squares Loss: 5.0000
Epoch 06 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 5.0000
Epoch 07 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 5.0000
Epoch 08 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 09 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 5.0000
Epoch 10 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 11 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 12 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 13 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 5.0000
Epoch 14 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 15 -> Train Sum-of-Squares Lo.ss: 4.0000 | Validation Sum-of-Squares Loss: 6.0000
Epoch 16 -> Train Sum-of-Squares

#### Accuracy

In [ ]:
test_pred = model.predict(X_test)

# Convert to class index
y_test_labels = np.argmax(y_test , axis=1)
pred_labels = np.argmax(test_pred, axis=1)

accuracy = accuracy_score(y_test_labels, pred_labels,)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.9736842105263158


#### Precision

In [ ]:
precision = precision_score( y_test_labels, pred_labels, average='weighted')
print("Test Precision:", precision)

Test Precision: 0.975877192982456


#### Recall

In [ ]:
sensitivity = recall_score( y_test_labels, pred_labels, average='weighted')
print("Test Sensitivity:", sensitivity)

Test Sensitivity: 0.9736842105263158
